### ISSUE TITLE
Unhandled rejection MongoError give 500

### ISSUE THREAD

**Issue by DidelotK** [ethanresnick/json-api#118]
Hi, i have  a 500 when mongo launch an error :p after missing validation

**Comment by ethanresnick** [comment]
Can you post more info about what you're seeing? A 500 for an uncaught mongoerror seems like it could be appropriate to me. What do you think you should be seeing?

**Comment by DidelotK** [comment]
I had this problem when I was giving wrong information (voluntarily) in a field with relationship, I would have liked a message like:
Error: [ {status : " 400 ", title : "Wrong relationship" }] , but I do not know if this is correct on the security level.

**Comment by Waxo** [comment]
Hi, i've tried with your [full, working example repo](http://github.com/ethanresnick/json-api-example) and tried to create two times a school with the same name. I got an 500 response error.

But in fact i think we should have a [409 Conflict error](http://jsonapi.org/format/#crud-creating-responses-409) according to the documentation.

Maybe i've done something wrong but since my app is based on the example i don't know how to fix this problem.

**Comment by ethanresnick** [comment]
@Waxo can you open a different issue for your problem, and include the payloads you're sending to the server.

@DidelotK I'm not sure if that's correct security-wise either, but I'll leave this issue open to consider it later.

**Comment by ethanresnick** [comment]
Supporting these cases is now possible in the v3 alpha! Closing.
