### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#151]
Whenever this library generates errors internally, the error code is always `undefined`. We should create, use, and document a set of codes, probably with a `ERR_JSON_API_` prefix. This would allow clients to check (hopefully stable) error codes instead of potentially changing error messages.

**Comment by ethanresnick** [comment]
Yup, this makes total sense.

**Comment by ethanresnick** [comment]
I'm a big fan of using URLs as error codes because: 1) they're already globally namespaced (no need for prefixes like `ERR_JSON_API`) and 2) if they can be derefenced, they can hold useful documentation at the destination. 

Accordingly, I've registered `jsonapi.js.org` as the domain for this library, and will create some urls on that domain for different types of errors. For now, the urls will be serialized in the `code` field. In the future, though, JSON:API may add a link for this.

**Comment by ethanresnick** [comment]
Closed by 900d6a7
