### ISSUE TITLE
Make the documentation controller optional

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#157]
It's a neat feature with MongoDB, where you generally don't have a concrete schema anywhere else. With Postgres though, if we want to know something about the schema, we just open up a database GUI and it tells us all we need to know.

Currently we have to create a documentation controller even though we're never going to use it. The empty `ResourceTypeRegistry` is just because I haven't implemented `KnexAdapter#standardizeSchema()`.

```js
const handleResourceRequest = new httpStrategies.Express(
  new controllers.API(actualRegistry),
  new controllers.Documentation(new ResourceTypeRegistry({}), {name: 'Example API'})
).apiRequest
```

**Comment by ethanresnick** [comment]
> With Postgres though, if we want to know something about the schema, we just open up a database GUI and it tells us all we need to know.

The generated docs were more meant for outside developers (e.g., if you're running a public API), so opening up a database GUI doesn't really cover that use case. And, long term, I've thought about redistributing the responsibilities so that, rather than the adapter providing the schema, the resource type description is the canonical statement of each model's schema, but adapters can provide helpers the user can call to autogenerate base type descriptions. In that world, the Documentation controller isn't adapter dependent at all, so no need to implement a `getStandardizedSchema`. 

All that said, none of the above is in place for v3, and I don't want to block v3 on it, so I'm 100% 👍  on making documentation controller optional for now. Can you open a PR for that? I guess the http strategy would just throw on `.docsRequest` if it wasn't initialized with a docs controller?

**Comment by carlbennettnz** [comment]
> Can you open a PR for that?

Coming up!
