### ISSUE TITLE
Sparse field sets don't work with inherited types

### ISSUE THREAD

**Issue by olokobayusuf** [ethanresnick/json-api#177]
- Suppose I have a base schema `A`, and another schema `B : A`
- Suppose we have two fields on `A`, `someField` and `anotherField`
- When performing a `GET` on `B` with sparse field sets, the field sets are ignored (likely because they are not defined directly on `B`):
```
api.somewhere.com/B?fields[B]=someField,anotherField
```
- Expected behaviour is that field sets are inherited, since `A`'s fields are `B`'s fields

**Comment by ethanresnick** [comment]
Under the JSON:API spec, the value in the square brackets for `?fields[TYPE]` must match the value serialized in the resource object's `type` key for the sparse fieldset list to take effect.

Subtypes are serialized with their parent type in the `type` key (an intentional decision discussed #149), so the library's current behavior is actually correct per the JSON:API spec.

If you want to filter the subtype's fields, then, you actually have to put the supertype in the query string:

```
api.somewhere.com/B?fields[A]=someField,anotherField
```
