### ISSUE TITLE
Incorrect Content-type on responses

### ISSUE THREAD

**Issue by twss** [ethanresnick/json-api#191]
Always responds with Content-Type of `application/json`

As per [the spec](https://jsonapi.org/format/#content-negotiation-servers):

> "Server **MUST** send all JSON:API data in response documents with the header `Content-Type: application/vnd.api+json` without any media type parameters.:

**Comment by ethanresnick** [comment]
If you're getting JSON back, it's probably because you're not putting `application/vnd.api+json` in your request's accept header. Serving `content-type: application/json` in that case is allowed by the spec (because JSON:API documents are also json documents). See https://github.com/json-api/json-api/pull/703 for details.

**Comment by twss** [comment]
That answers my next question too.

Whilst I don't necessarily agree with the breaking of the spec at such an early/fundament stage of the client-server interaction (as it makes the case for enforcement of the JSON-API spec in other areas seem "open for discussion"), I do understand why it's been done.

**Comment by twss** [comment]
One thing I will say. The upcoming 1.1 spec seems to enforce that requirement: https://jsonapi.org/format/1.1/#content-negotiation-all

> The JSON:API media type is `application/vnd.api+json`. Clients and servers **MUST** send all JSON:API data using this media type in the `Content-Type` header.

It seems pretty explicit.

**Comment by ethanresnick** [comment]
This response is not breaking the spec; it's just not using the spec. In other words, the server is, at this point, just sending back "plain json", rather than "JSON:API data", because the client hasn't asked for JSON:API data. There's a bit more detail about my POV [here](https://github.com/json-api/json-api/pull/673#discussion_r30962383). 

Anyway, this is not a question I'm particularly keen to re-open. I will say though that, as the author of most of the content negotiation language you're citing, I can tell you for sure that this behavior is intended to be allowed :)

**Comment by twss** [comment]
> Anyway, this is not a question I'm particularly keen to re-open. I will say though that, as the author of most of the content negotiation language you're citing, I can tell you for sure that this behavior is intended to be allowed :)

A JSON-API-compliant server that "isn't using the spec" isn't JSON-API-compliant?

Fair enough, I consider myself told. Might want to address the inconsistency/ambiguity in your POV/spec doc for v1.1. A *MUST* is not be optional. So either this or the spec wording is wrong. (*SHOULD*/*MAY*?)
