### ISSUE TITLE
Dasherizing member names

### ISSUE THREAD

**Issue by andrewbranch** [ethanresnick/json-api#30]
The JSON API spec recommends that member names be dasherized. I think we should be dasherizing by default, but there probably needs to be an easy way to opt out of it. There are also some challenges to un-dasherizing (camelizing) some names. For instance, say you have a Mongoose schema like:

``` javascript
let PersonSchema = new mongoose.Schema({
  name: String,
  imageURL: String
});
```

It’s easy to dasherize `imageURL` to `image-url` on outgoing responses, but on an incoming POST request, for example, you might have a request body that looks like

``` json
{
  "data": {
    "type": "people",
    "attributes": {
      "name": "Andrew",
      "image-url": "http://placehold.it/100x100"
    }
  }
}
```

the camelization of `image-url` will result in `imageUrl` rather than `imageURL`.

So, I’m wondering if we should build in a way to customize the dasherized/camelized relationship. In my project, I’m handling this by adding a virtual field called `imageUrl` on the schema.

We could kill two birds (the “opt-in/opt-out” bird and the “customized transform” bird) with one stone by allowing users to specify a pair of functions when defining resources:

``` javascript
import camelize from 'camelize';
import dasherize from 'dasherize';

registry.type('people', {
  adapter: adapter,
  urlTemplates: {
    "self": "/people/{id}"
  },
  transformMemberNames: {
    fromRequest: camelize, // request comes in dasherized, camelize it before accessing store
    fromStore: dasherize   // names are camelized in store, dasherize before sending response
  }
});
```

Maybe that particular case, simple camelize/dasherize functions could be the default, but it would be easy to override on a per-resource basis, checking for special cases like

``` javascript
fromRequest: dasherized => {
  if (dasherized === 'image-url') {
    return 'imageURL';
  }
  return camelize(dasherized);
}
```

or to opt out of transformations:

``` javascript
transformMemberNames: {
  fromRequest: name => name,
  fromStore: name => name
}
```

I’m definitely not set on the exact naming above, maybe `fromRequest` and `fromStore` would be better as `deserialize` and `serialize`. But what do you think of going in this direction?

**Comment by ethanresnick** [comment]
One observation: it seems like whether to dasherize is (or should be) an API-wide property, and not a property specific to each resource type. Right? If so, requiring the user to specify serialization/deserialization functions in each resource description seems a bit cumbersome. 

Also, I'd rather have a declarative way for the user to specify exceptions to the case-transformation rules, in the same way the user can replace the auto-generated `friendly-name` that's used in the JSON documentation with a custom one simply by specifying it in `info`. 

Considering these two issues together, what do you think about a design like the following:
  - First, we'd extend the resource type description format with a new `"behaviors"` key like so:
  ```
  { 
    //urlTemplates, dbAdapter, etc. here.
    "behaviors": {
      "dasherizeOutput": {
        "enabled": true,
        "exceptions": {
          // below, putting the camel-case name as the key is arbitrary; 
          // as long as the same format is always the key, we'll be fine
          "imageURL": "image-url"
        }
    }
  }
  ``` 
  (Corresponding to this new key, we'd add a behaviors getter/setter to the ResourceTypeRegistry, like the getter/setters that already exist for the other keys.)

  - Second, we add a new argument, called `defaults` to the ResourceTypeRegistry constructor. This argument would accept an object with keys whose values should be used as the default when code reading a property of the resource type from the registry. For starters, this argument would probably support keys for `dbAdapter`, `urlTemplates`, and `behaviors`. So the user could construct the ResourceTypeRegistry like so:

  ```
  const adapter = new MongooseAdapter(models);
  const resourceDefaults = {
    "dbAdapter": adapter, 
    "behaviors": {
      "dasherizeOutput": { "enabled": true}
    }
  };
  const registry = new ResourceTypeRegistry([], resourceDefaults);
  ```

  - Finally, code that needs to know whether dasherization is enabled (like the documentation controller, and the API controller) looks that up from the registry with `registry.behaviors("type-name").dasherizeOutput.enabled`. (Technically, `(registry.behaviors("type-name").dasherizeOutput || {}).enabled`, but we could probably make the ResourceTypeRegistry always return at least a blank object at the `dasherizeOutput` key, so that this isn't necessary.)

As I see it, this approach has a few advantages:

1. The `behaviors` key is something I've wanted to add anyway, to support enabling other transforms more declaratively, like whether a field is readonly.

2. Allowing the ResourceTypeRegistry to take defaults solves the annoying problem of having to set the adapter manually on each resource type (as done [here](https://github.com/ethanresnick/json-api-example/blob/master/src/index.js#L29)). Then `dasherizeOutput` just becomes another one of these defaults. (Allowing the user to specify default URI templates could be a huge win too.)

3. In the unlikely event that the user wants to override the `dasherizeOutput` setting for a particular resource type, there's a way to do so. Also, by making this config option live in the resource type registry, we don't have to add a new structure/class for handling truly API-wide configs (i.e. that can't be overridden on each resource) just yet.

Thoughts?

**Comment by andrewbranch** [comment]
> One observation: it seems like whether to dasherize is (or should be) an API-wide property, and not a property specific to each resource type. Right? If so, requiring the user to specify serialization/deserialization functions in each resource description seems a bit cumbersome.

True, I guess I was only thinking about my own implementation, which at the moment is simple enough that I’m declaring my resource descriptions within a loop. I agree it should be a global setting.

> Also, I'd rather have a declarative way for the user to specify exceptions to the case-transformation rules, in the same way the user can replace the auto-generated friendly-name that's used in the JSON documentation with a custom one simply by specifying it in info.

I think we may just have a difference in API preference here. Couldn’t exceptions be programmatically made in `beforeSave` and `afterRender`? Personally, as a user of this package, I think I’d rather define my edge-case behaviors (like a weird camelization) functionally rather than in a big configuration object. I think that keeps this API light without removing any power.

That said, this is your project, I need this feature, so if you disagree I’ll implement it the way you suggested.

**Comment by ethanresnick** [comment]
> I think we may just have a difference in API preference here. Couldn’t exceptions be programmatically made in `beforeSave` and `beforeRender`?

Yeah, this is probably partially a preference thing. But I think there are a couple non-aesthetic reasons for doing it declaratively too. 

The first is the auto-generated documentation. The documentation generator needs to know the user-facing name of each property, and it can't easily run `beforeRender` to get that, since 1) there's no resource for it to call the function with (it would have to fabricate one, which is a bit of a pain) and 2), more importantly, `beforeRender` could have side effects that shouldn't be tripped just by generating the documentation. 

Also, having to define the exception in both `beforeRender` and `beforeSave` seems more error prone to me, i.e. the user may remember to add it in one place but not the other.

> That said, this is your project, I need this feature, so if you disagree I’ll implement it the way you suggested.

Ok, thanks. That said, if you feel strongly about something, please don't hesitate to push back; you're likely seeing something I'm missing.

**Comment by andrewbranch** [comment]
> auto-generated documentation

Ahhhh. Yeah, for generating documentation I guess everything _has_ to be declarative. That makes sense.

**Comment by ethanresnick** [comment]
Cool, cool. 

Btw, the documentation stuff should be quite simple to implement. I think it'd just be sticking in a line right [here](https://github.com/ethanresnick/json-api/blob/master/src/controllers/Documentation.js#L78) that says `field.name = [name from behaviors key] || field.name`, where you can get the name from the behaviors key outside the loop using `this.registry`

**Comment by andrewbranch** [comment]
Doing

```js
{
  exceptions: {
    "something-dasherized": "somethingDifferent"
  }
}
```

actually becomes kind of a bummer when transforming in the reverse direction—having to iterate through exceptions to determine if there is a key whose value matches the provided attribute. Is there a better way of declaring exceptions, or is there a better way of doing that transformation that I’m not thinking of?

**Comment by ethanresnick** [comment]
> Is there a better way of declaring exceptions, or is there a better way of doing that transformation that I’m not thinking of?

The best method I can think of is to keep some hash that acts to cache/memoize all this stuff, so that the regexs + iteration don't have to happen over and over. This still involves iterating over each `exceptions` object once, to prepopulate the cache with the exceptions, but it doesn't seem to bad. Something like:

```
// build cache for this type, prepopulating it 
// with the type's exceptions
var cache = Object.assign({}, exceptions);

// here, transform is standing in for the dasherize 
// or camelize steps, which would be analogous
changeCase(word) {
  if(cache[word]) {
    return cache[word];
  }
  else {
     let transformed = "..."; // do some regex etc here to actually transform the word
    cache[word] = transformed;
    return transformed;
}
```
Where `cache` is a map that would be prepopulated with the exceptions.

Thoughts?

**Comment by maysale01** [comment]
Sidebar: Creating a dasherized member cache in the MongooseAdapter would resolve an issue I'm having where camel case model names are getting fubard by the default singular inflector from the `pluralize` library.

**Comment by ethanresnick** [comment]
@maysale01 I'm not sure what you're trying to do exactly, but you may be using the wrong method... `getModelName` is meant to take a JSON API type string (assumed currently to be plural and dasherized) and turn it into a model name, assumed to be singular and pascal-cased. I.e., it maps "people" to "Person" or "encoding-profiles" to "EncodingProfile".

If you want/need to use a plural mongoose model name in your app, I think you should set the pluralizer to just be the identity function (so that it doesn't do any pluralization, since the model names will already be plural). You can do this on instantiation of the adapter, e.g.:

```
const inflectors = {plural: (it => it), singular: pluralize.singular };
new MongooseAdapter(models, inflectors);
```

If that doesn't work, though, or you have any other questions, please open another issue! I want to keep the discussion focused here.

**Comment by maysale01** [comment]
@ethanresnick I resolved the issue by following the dasherized convention with my model registration and endpoints. I wasn't aware of the recommendation in the JSONAPI spec for dasherized member names.    
    
Thanks for replying and contributions!

**Comment by ethanresnick** [comment]
Closing per https://github.com/ethanresnick/json-api/pull/34#issuecomment-375486587

**Comment by drummy2** [comment]
I currently have this from the demo and want to stop all pluralization as above.

`var adapter = new API.dbAdapters.Mongoose(models);`

I then use the example above to add inflectors by requiring pluralize but I get the following error

> TypeError: toTypeName is not a function
    at new MongooseAdapter (/home/mongo-api/json-api-example/node_modules/json-api/build/src/db-adapters/Mongoose/MongooseAdapter.js:44:30)
    at Object.<anonymous> (/home/mongo-api/json-api-example/src/index.js:33:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
