### ISSUE TITLE
Errors in beforeSave and beforeRender hooks cause hangs

### ISSUE THREAD

**Issue by carlbennettnz** [ethanresnick/json-api#55]
```javscript
beforeRender: function() {
    notAFunction()
}
```

Related: I can't figure out how I'm supposed to handle errors there. You mentioned something about the `APIError` type, but throwing or returning that causes hangs too. How do I reject a request entirely?

**Comment by ethanresnick** [comment]
I'll look into this later tonight. You're right about both problems, but I'm not sure what's going on here.

**Comment by ethanresnick** [comment]
Actually, I probably won't be able to look into these issues until early next week, but I'll get to them ASAP.

**Comment by carlbennettnz** [comment]
No problem. I'll give some of the easier ones a shot over the weekend.

**Comment by ethanresnick** [comment]
:+1:

**Comment by ethanresnick** [comment]
@carlbennettnz Can you check if this is still an issue? I think it should have been fixed by https://github.com/ethanresnick/json-api/commit/5018d8f0063bf37e654158d29a204a198a6b7c5c. I.e., you should now be able to throw an error and have the request aborted and the error sent (in jsonapi format) back to the client.

**Comment by carlbennettnz** [comment]
Works beautifully :+1:
