### ISSUE TITLE
Example using express-simple-router

### ISSUE THREAD

**Issue by seawatts** [ethanresnick/json-api#60]
Hey I am trying to use the json-api library and it says you can hook up the express-simple-router. Do you have an example?

**Comment by ethanresnick** [comment]
See https://github.com/ethanresnick/json-api-example/blob/express-simple-rout/src/index.js for a partial example. As you can see, using express-simple-router is actually somewhat more verbose in this case than using the [chained .route() calls](https://github.com/ethanresnick/json-api-example/blob/master/src/index.js#L57) that are built into express, because you need one route object for each http method. But it has the advantage of allowing you to move your routes to a separate json file and then just `require()`ing that object, and it also works with express-simple-firewall, though that is not well-documented (you'll have to look at the inline [code documentation](https://github.com/ethanresnick/express-simple-firewall/blob/master/lib/simple-firewall.js) for help with that).

**Comment by seawatts** [comment]
Awesome! Thanks @ethanresnick for being so quick =)
