### ISSUE TITLE
Delete works in curl but not from ajax request

### ISSUE THREAD

**Issue by seawatts** [ethanresnick/json-api#67]
I'm able to perform a GET request via ajax through a proxy (I'm using ember and --proxy). However, when I perform a DELETE I get a 500 error. 

```
An unknown error occurred while trying to process this request.
```

The ajax request has `Accept: application/vnd.api+json`

When I call it with curl

```
curl -X DELETE -H "Accept: application/vnd.api+json" 'http://127.0.0.1:3000/api/1/users/55e34b670d69db906f4cefea'
```

I get a 204 back. 

But when I use Postman and make a call directly to the server which looks the same as the curl command I actually get a 400

```
Request contains invalid JSON.
```

Any ideas? I'm having a hard time trying to debug the code. Is there any logging I can turn on?

**Comment by seawatts** [comment]
Hmm looks like its throwing
```
[TypeError: content-type header is missing from object]
```
When calling `buildRequestObject`

**Comment by seawatts** [comment]
Alright, so it seems like ember-cli `ember serve --proxy` adds `content-length: 0` to `DELETE` methods.

**Comment by seawatts** [comment]
I added 
```js
    if (it.method === "delete") {
      delete req.headers["content-length"];
    }
```

right before the check to see if it has a body and now it works. How do you feel about that solution?

**Comment by ethanresnick** [comment]
Hi @seawatts. This is very interesting behavior, so thanks a lot for reporting it!

I don't think the solution is quite as simple as removing `Content-Length` on delete requests, because some JSON API `DELETE`'s actually do [have a body](http://jsonapi.org/format/#crud-updating-to-many-relationships) (a decision which was [controversial](https://github.com/json-api/json-api/issues/838), but that's neither here nor there), so they'll need that header to be parsed successfully.

Therefore, I think the solution is to treat an empty body equivalently to the request not having a body at all. So, here's what I'd do:

First, rename the function in the `ExpressStrategy` from `hasBody` to `hasNonEmptyBody`, and add a `Content-Length != 0` check to it.

Then, in the [Request class](https://github.com/ethanresnick/json-api/blob/master/src/types/HTTP/Request.js#L7), I'd leave the field called `hasBody` for simplicity, but mention in the field's comment that it means "has a (non-empty) body".

Does that sound good? Are you willing to whip up a PR?

**Comment by seawatts** [comment]
Thanks for the detailed explanation :+1: That sounds great! I can't get to the PR today, but maybe some time this week.

**Comment by ethanresnick** [comment]
No worries, @carlbennettnz took care of it :) Thanks again for the helpful report.

**Comment by ethanresnick** [comment]
Reopening this per @seawatts' comment [here](https://github.com/ethanresnick/json-api/commit/19e16edfb58ee2b5f2573a9e2d1d09cb73d05050#commitcomment-13202528). 

@seawatts can you please add a failing test case for this (in the create resource integation tests file), so we don't get more regressions in the future, and then I'll work on adding a fix :)

**Comment by ethanresnick** [comment]
Ok, I really believe this isn't happening anymore, and there's now [an integration test](https://github.com/ethanresnick/json-api/pull/162/commits/30f24b671f6bd87af18d015b82ec202becf25640) to (hopefully) prove it. For anyone effected, please comment if this is still happening to you on latest v3.
