### ISSUE TITLE
Non Express/Connect middleware compliant

### ISSUE THREAD

**Issue by sescobb27** [ethanresnick/json-api#91]
Hi, I was wondering why did you use that kind of request handling approach instead of the old express way of handling incoming request and letting users use your lib as a express middleware?.
I'm asking because we have an express API and we want to adopt JSON API and we found your library, it is awesome and thank you for it, but if we use it we are forced to use it in a non standard way and to change  A LOT of code in our backend and that's not a choice.

Is there another way we can use it without that `Front.apiRequest`.?

**Comment by ethanresnick** [comment]
Hi. Thanks for your nice words about the library! I think you should be able to make it work for your use case relatively easily.

First, though, here's why it works the way it does. Basically, I wanted my library to be usable with server libraries beyond express (like koa, hapi, etc), which have different signatures for the functions they use to handle an incoming request and different formats of the request/response objects that they ask those functions to manipulate. I wanted to shield the main code in this library from all those framework-specific differences. Therefore, there's a concept of an "http strategy", which can be different for each framework. The HTTP strategy handles the incoming request in whatever format the framework provides and converts it to a neutral [Request](https://github.com/ethanresnick/json-api/blob/master/src/types/HTTP/Request.js) object that the rest of this library uses; then, when the library's done it hands back a framework-neutral  [Response](https://github.com/ethanresnick/json-api/blob/master/src/types/HTTP/Response.js) object to the strategy, and the strategy converts that neutral response to a format useable by the particular server framework.

Now, the `Front.apiRequest` method that you alluded to is a method on the express http strategy, so it does conform to Express's standard `(req, res, next)` signature. That means that you can very easily use other middleware before it runs, like so:

```
app.get("/posts", checkAuthenticated, otherMiddleware, blahEtc, Front.apiRequest.bind(Front)
```

The only thing you can't do quite as easily is call other middleware _after_ `Front.apiRequest`, because it sends the response as soon as it's done working. However, if you need to override that behavior, you should be able to subclass the [ExpressStrategy](https://github.com/ethanresnick/json-api/blob/master/src/http-strategies/Express.js) relatively easily, then redefine [`sendResources`](https://github.com/ethanresnick/json-api/blob/master/src/http-strategies/Express.js#L67) in that class to fit your needs.

Does that help?

**Comment by sescobb27** [comment]
yeah, that totally make sense, thank you so much for your time and your explanation :smile:.

**Comment by ethanresnick** [comment]
Great! If that works, I'm gonna give this a close :)
