### ISSUE TITLE
PATCH should call update in Mongo adapter

### ISSUE THREAD

**Issue by seawatts** [ethanresnick/json-api#92]
The current implementation seems to call [`.save()`](https://github.com/ethanresnick/json-api/blob/master/src/db-adapters/Mongoose/MongooseAdapter.js#L254) on the model when issuing a `PATCH` request. By doing so this calls the mongoose `save` [lifecycle hook](http://mongoosejs.com/docs/middleware.html#post) I believe calling `.update()` on the document should fix this. (I haven't tested this out yet)

It also seems that you referenced Mongoose 4.x, which has been released, is [this comment](https://github.com/ethanresnick/json-api/blob/master/src/db-adapters/Mongoose/MongooseAdapter.js#L185) just out of date?

**Comment by ethanresnick** [comment]
Running the save lifecycle hook in v2 was intentional; that approach was used for the more complete validation that the read-then-resave pattern allows. However, it came with other downsides and has been changed in v3 to work as you requested. See the v3 changelog for details + rationale. https://github.com/ethanresnick/json-api/blob/06519812803fa72aa097ba0a6e88ad1ac3d715c2/UPGRADING.md#mongoose-behaviormongooseadapter
